authenticate/urls.py
from .import views
from django.urls import path

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authenticate.urls')),
    path('products/',include('product.urls', namespace='products')),
]
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

product/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .import views

app_name= 'product'

urlpatterns = [
    path('', views.productlist, name='product_list'),
    #path('<int:id>', views.productdetail, name='product_detail'),
    path('<slug:product_slug>', views.productdetail, name='product_detail'),
]

authenticate/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify


# Create your models here.
class Product(models.Model):
    CONDITION_TYPE =(
        ("New" , "New"),
        ("Used" , "Used")
    )



    #contains all the product information
    name = models.CharField(max_length=100)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField(max_length=500 )
    condition = models.CharField(max_length=100, choices=CONDITION_TYPE)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    brand = models.ForeignKey('Brand', on_delete=models.SET_NULL, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=5)
    created = models.DateTimeField(default=timezone.now)

    slug = models.SlugField(blank=True , null=True)

    def save(self, *args, **kwargs):
        if not self.slug and self.name:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    #classes for product images

class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image =  models.ImageField(upload_to='product/', blank=True, null=True)

    def __str__(self):
        return self.product.name
    class Meta:
        verbose_name = 'Product Image'
        verbose_name_plural= 'Product Images'

    #classes for product category

class Category(models.Model):
    category_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='category/', blank=True, null=True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural= 'categories'

    def __str__(self):
        return self.category_name

     #classes for product   brand

class Brand(models.Model):
    brand_name = models.CharField(max_length=50)
    

    class Meta:
        verbose_name = 'brand'
        verbose_name_plural= 'brands'

    def __str__(self):
        return self.brand_name

authenticate/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
#from django.db.models.base import Model
#from django.forms import fields
#from django.forms import widgets
#from django.forms.widgets import Widget
#from django.forms import fields

class SignUpForm(UserCreationForm):
    email =forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'}))
    first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
    last_name  = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))


    class Meta:
        model = User
        fields=('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'User Name'
        self.fields['username'].label =""
        self.fields['username'].help_text = '<div class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></div>'

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Enter Password'
        self.fields['password1'].label =""
        self.fields['password1'].help_text = '<div class="form-text text-muted"><small><ul><li>Your password can\’t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\’t be a commonly used password.</li><li>Your password can\’t be entirely numeric.</li></ul></small></div>'


        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['password2'].label =""
        self.fields['password2'].help_text = '<div class="form-text text-muted"><small>Enter the same password as before, for verification.</small></div>'

authenticate/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import SignUpForm




def home(request):
    return render(request, 'authenticate/home.html', {})

def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)


        if user is not None:
            login(request, user)
            # Redirect to a success page.
            messages.success(request, ('Logged in Successfully'))
            return redirect('home')


        else:
            # Return an 'invalid login' error message.
            messages.success(request, ('Error while Logging In!  Please Try Again...'))
            return redirect('login')


    else:
        return render(request, 'authenticate/login.html', {})
 
def logout_user(request):
        logout(request)
# Redirect to a success page.
        messages.success(request, ('You have been Logged Out!'))
        return redirect('home')

def register_user(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(request, username=username, password=password)
            login(request, user)
            messages.success(request, ('Hooray!! You have been Registeres successfully'))
            return redirect('home')


      
    else:
        form = SignUpForm()

        context = { 'form': form }
        return render(request, 'authenticate/register.html', context)

product/views.py
from django.shortcuts import render
from .models import Product
# Create your views here.
def productlist(request):
    productlist = Product.objects.all()
    #print(productlist)
    context ={'product_list' : productlist}
    template ='Product/product_list.html'
    return render(request, template, context)

def productdetail(request, product_slug):
    print(product_slug)
    productdetail = Product.objects.get(slug=product_slug)
    template ='Product/product_detail.html'
    context ={'product_detail' : productdetail}
    return render(request, template, context)

authenticate/templates/authenticate/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
  <br/>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-gradient">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">ShopYangu</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>


      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout'%}">Logout</a>
        </li>
      {% else %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}" tabindex="-1" aria-disabled="false">Register</a>
        </li>
{% endif%}
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

        <br/>
  <div class="container">
      {% if messages %}
          {% for message in messages%}
            <div class="alert alert-warning alert-dismissable fade show" role="alert">
              <button type="button" class="btn-close ml-auto" data-bs-dismiss="alert" aria-label="Close">
                    <!--small><sup>x</sup></small-->
              </button>
              {{ message }}
            </div>
          {% endfor %}
      {% endif %}

        {% block content %}
        {% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>

authenticate/templates/authenticate/home.html
{% extends 'authenticate/base.html' %}
{% block content %}


<h1>This is home page</h1>

 {% if user.is_authenticated %}
        <p>Name:     {{ user.first_name }} {{ user.last_name }} </p>
        <p>Username:  {{ user.username }} </p>
        <p>Password:  {{ user.password }}</p>
        <p>Email:     {{user.email}}</p>
        
{% endif %}




{% endblock %}

authenticate/templates/authenticate/login.html
{% extends 'authenticate/base.html' %}
{% block content %}


<h3 class="text-center">Login</h3>

<div class="col-md-6 offset-md-3">


<form method ="POST">
{% csrf_token %}
        <div class=" mb-3">
            <input type="text" class="form-control"  placeholder="Enter Username" name="username">
        </div>
        <div class="form-group">
            <input type="password" class="form-control" placeholder="Enter Password" name="password">
        </div> 
    <br/>
    <button type="submit" class="btn btn-secondary">Login</button>
    </form>
 {% endblock %}
<div>

authenticate/templates/authenticate/register.html
{% extends 'authenticate/base.html' %}
{% block content %}


<h1 class="text-center">Register</h1>

<div class="col-md-6 offset-md-3">
    <form method="POST" action="{% url 'register' %}">
        {% csrf_token %}
        {% if form.errors %}
         <div class="alert alert-warning alert-dismissable fade show" role="alert">
              <button type="button" class="btn-close ml-auto" data-bs-dismiss="alert" aria-label="Close">
                    <!--small><sup>x</sup></small-->
              </button>
             
            <P> Your Form Has Errors.......</p>

            {% for field in form %}
            {% if field.errors %}

                {{ field.errors }}
            {% endif %}


            {% endfor %}
            </div>

        {% endif %}

        {{ form.as_p }}

        <input type="submit" value="Register" class="btn btn-secondary">
    </form>
 </div>
{% endblock %}

product/templates/Product/product_detail.html
<h2>One Product</h2>


{{product_detail}}
{{product_detail.description}}

product/templates/Product/product_list.html
<h1>OUR PRODUCTS</h1>

{% for product in product_list%}



<h2><a href="{% url 'products:product_detail' product.slug %}">{{ product }}</a></h2>

{% endfor %} 